SHELL := /bin/bash

all:
	pdflatex xdusek21-IdentityTheft.tex
	rm xdusek21-IdentityTheft.aux xdusek21-IdentityTheft.log xdusek21-IdentityTheft.snm xdusek21-IdentityTheft.nav xdusek21-IdentityTheft.out xdusek21-IdentityTheft.toc